name: 'Jekyll SEO Generator'
description: 'Generate SEO tags for Jekyll'
author: Alpha <alphagma@gmail.com>
runs:
  using: 'node16'
  main: 'dist/index.js'

inputs:
  openai-api-key:
    description: 'OpenAI API key'
    required: true
  github-token:
    description: 'GitHub token'
    required: true

branding:
  icon: 'search'
  color: 'blue'
