export const generateReport = async (results) => {
    const lines = [];

    lines.push(`# Updated files`);
    lines.push(``);
    lines.push(`| File | Generated description |`);
    lines.push(`| :--- | :--- |`);
    results.forEach(r => {
        lines.push(`| \`${r.page}\` | ${r.description} |`);
    });
    lines.push(``);
    lines.push(`These changes were automatically generated by [Jekyll SEO AI Action](https://github.com/AlphaGit/jekyll-seo-ai-action).`);

    return lines.join(`\n`);
};
